[app]
  port = 80
  debug = false
  logLevel = "warning"
  version = "v2.3.0"

[[availableLanguages]]
  Locale = "en-US"
  Name = "English"
  File = "./locales/en.ini"

[[availableLanguages]]
  Locale = "fr-FR"
  Name = "Français"
  File = "./locales/fr.ini"

[[availableLanguages]]
  Locale = "zh-CN"
  Name = "中國語文"
  File = "./locales/zh.ini"

[auth]
  path = "/recalbox/share/system/.config/manager-web/"
  file = "credentials.auth"

[recalbox]
  pythonSettingsFile = "/usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"
  configScript = "/recalbox/scripts/recalbox-config.sh"

[recalbox.bios]
  filesPath = "/recalbox/share/bios/"
  md5FilePath = "/recalbox/share_init/bios/readme.txt"
