[app]
  port = 8888
  debug = true
  logLevel = "debug"
  version = "v2.3.0"

[availableLanguages]
  en-US = "./locales/en.ini"
  fr-FR = "./locales/fr.ini"
  zh-CN = "./locales/zh.ini"

[auth]
  path = "/recalbox/share/system/.config/manager-web/"
  file = "credentials.auth"

[recalbox]
  pythonSettingsFile = "/usr/lib/python2.7/site-packages/configgen/settings/recalboxSettings.pyc"
  configScript = "/recalbox/scripts/recalbox-config.sh"
